import { NextResponse } from 'next/server';
import { authorizeMediaRead } from '@/lib/media';
import { storage } from '@/lib/storage';

export const runtime = 'nodejs';

/**
 * The only way to read a media object.
 *
 * Authorization happens here, on the image request, then a short-lived signed
 * URL is minted and redirected to so the bytes come from object storage rather
 * than through this server. Nothing hands out a durable public URL.
 *
 * Every denial answers 404. Distinguishing "pending moderation" from "does not
 * exist" would confirm to a stranger that a photo was uploaded.
 */
export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const variant = new URL(req.url).searchParams.get('v') === 'thumb' ? 'thumb' : 'original';

  const auth = await authorizeMediaRead(id, variant);
  if (!auth.ok) return NextResponse.json({ error: 'not found' }, { status: 404 });

  const driver = storage();

  // A thumbnail is generated by the uploading browser, so it can be absent for
  // older or seeded rows. Fall back to the original rather than showing a hole.
  let key = auth.key;
  if (variant === 'thumb' && !(await driver.head(key))) key = auth.asset.storageKey;

  const url = await driver.signedReadUrl(key, 300);
  return NextResponse.redirect(new URL(url, req.url), {
    status: 302,
    headers: { 'cache-control': 'private, max-age=60' },
  });
}
